log:
  level: WARN

global:
  checkNewVersion: true
  sendAnonymousUsage: false

providers:
  docker:
    exposedByDefault: false
  file:
      directory: /etc/traefik/dynamic
      watch: true

api:
  dashboard: true

serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: :443
    http:
      tls: true


certificatesResolvers:
  letsencrypt:
    acme:
      email: acme@tobsa.wtf
      storage: /etc/traefik/certs/acme.json
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: hetzner